# Generated by Django 4.2.6 on 2023-10-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category_image', models.ImageField(blank=True, upload_to='category_image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prouct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_image', models.ImageField(blank=True, upload_to='product_image')),
                ('description', models.TextField(blank=True)),
                ('summary', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='prouct',
            index=models.Index(fields=['id', 'slug'], name='shop_prouct_id_119a79_idx'),
        ),
        migrations.AddIndex(
            model_name='prouct',
            index=models.Index(fields=['name'], name='shop_prouct_name_6177b1_idx'),
        ),
        migrations.AddIndex(
            model_name='prouct',
            index=models.Index(fields=['-created'], name='shop_prouct_created_6ec562_idx'),
        ),
    ]
