# Generated by Django 4.2.6 on 2023-10-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouct',
            new_name='Product',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_name='shop_prouct_id_119a79_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_name_a2070e_idx',
            old_name='shop_prouct_name_6177b1_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_created_ef211c_idx',
            old_name='shop_prouct_created_6ec562_idx',
        ),
    ]
