# Generated by Django 4.2.7 on 2023-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
